#
# .travis.yaml contains YAML-formatted (http://www.yaml.org/) build
# instructions for continuous integration via Travis CI
# (http://docs.travis-ci.com/).
#

notifications:
    email: false

language: c

compiler:
    - gcc

env:
    matrix:
        # Linux x86
        - OS_ID=0.4.4
        # Linux x64
        - OS_ID=0.4.40

before_install:
    - sudo apt-get update

install:
    # gcc-multilib:
    #   For building 32b binaries on a 64b host (not necessary when we build
    #   for 64b).
    # libc6:i386:
    #   For running the 32b bootstrap rebol ("r3-make") on a 64b host.
    - sudo apt-get install -y gcc-multilib libc6:i386
    # Fetch a Rebol bootstrap binary, which is needed for building Rebol.
    - wget http://www.rebol.com/r3/downloads/r3-a111-4-2.tar.gz
    - tar xvzf r3-a111-4-2.tar.gz
    - cp r3 make/r3-make

script:
    - cd make/
    - make -f makefile.boot OS_ID=${OS_ID}
