#
# .travis.yaml contains YAML-formatted (http://www.yaml.org/) build
# instructions for continuous integration via Travis CI
# (http://docs.travis-ci.com/).
#

notifications:
    email: false

language: c

compiler:
    - gcc

env:
    matrix:
        # Linux x86, debug
        - OS_ID=0.4.4
        # Linux x64, debug
        - OS_ID=0.4.40
        # Linux x64, release
        - OS_ID=0.4.40 NDEBUG=1

# Force new container-based infrastructure.
# Ref: http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

addons:
    apt:
        packages:
            # For building 32b binaries on a 64b host (not necessary when we
            # build for 64b):
            - gcc-multilib
            # For running the 32b bootstrap rebol ("r3-make") on a 64b host:
            - libc6:i386


install:
    # Fetch a Rebol bootstrap binary, which is needed for building Rebol.
    - wget http://www.rebol.com/r3/downloads/r3-a111-4-2.tar.gz
    - tar xvzf r3-a111-4-2.tar.gz
    - cp r3 make/r3-make

script:
    - cd make/
    - make -f makefile.boot OS_ID=${OS_ID}
