#
# .travis.yaml contains YAML-formatted (http://www.yaml.org/) build
# instructions for continuous integration via Travis CI
# (http://docs.travis-ci.com/).
#

notifications:
    email: false

language: c

compiler:
    - gcc
    - g++

env:
    matrix:
        # Linux x86, release
        - OS_ID=0.4.4 REL=1
        # Linux x64, debug
        - OS_ID=0.4.40
        # Linux x64, release
        - OS_ID=0.4.40 REL=1

        # Windows x86, release
        - OS_ID=0.3.1 REL=1 TOOLS=i686-w64-mingw32-
        # Windows x64, release
        - OS_ID=0.3.40 REL=1 TOOLS=x86_64-w64-mingw32-

    global:
        # travis encrypt AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - secure: "Vzw/uhZ2ni42j2MJpOj5daTBuQnuLfUs/qBZ5JLrDZCT4PTwdsUvbO8o6+p/+usDshT3cs4koRqqHiQ9mRnrdkP4FGqZWmwfjF2/7kJx39qewV3c11tMqjLHZNMonnaszxcnRyt3WiU+U7v88YRE/0X1kIjrsnBCTsVs3iD8RYuG87KR0lPFnt/gJXtzZKvmgo2fTMRr2XNCcijuwZBwh/vAcm7Cu6FUhEIDFjnCr+rAW4iuNtydVZxHF0QVBWUN3jVVWfcuFiJYg8ROLUmG1HB82MGgQsZTou8QsxhQHF/uyhOPfAIN2QDtsflBQPz/chfk/lDef9vczoTxQaacWoh8rRkTQdAeGfMm0+9vxHxFunt2ojD+2932HQB9As2p+Viqbe0E4MQTerBqAagTF9dfz3b8FjeAUBleU9aiiHusV8Lq/m7NN3bPBZyA9RKF48f3sFDEnQIvyO4mwFqW0rZDzGX6PRBQcB71NvfsNteQIF2rJs8CDcfmBrnQPysb4GG4TDIZsz/asnb6sUnI/xoWOKnJDvnfK8GxrfCoHMpqW3ubctwH+jjmefo6fIwDJ8hRWc44HFaFQBtJmzNF7tTNlYTp4+jC2KYVmU7HHXZYaKrktSpinOUwYTPnFCyMNqXOiGOm0waUj70nu0s1qupJ+uGqr6T8KKqYX2u5nPE="
        # travis encrypt AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - secure: "D4j8kVEG2OJXDgNbGD+2IyDX6KJcUy1MbnfrLDNlHoZa87ik4HIw7j09A0XdDvREYk2kSgYc5W79EzKbU+y9ZT8CAGnr8tjhwPHFWr2XR4XXQls0I4QT+EG448EMoUcFVYmAoXCmftQT80FznU1OhZoi/KBHwgd4pGoFeEs1zl64lnHnijscydXBSxwBCvOxTEDdIC+Mu3zF7b2GqOR+qP80QAZc5aPashs9EV7GrZiaF1cu502gQsWjr73KQV1lPB5dnAji1L5Y3+SLjawDlT7ITv8FzACsriPSkYgG2MLr7Pu3wm6Qt869VZkLa4lpasstZpm3q8KrebC1Rq4Y5YbaFFFh/s/Z+ajCGeFwmXgD+MNM4QyEJFbZ/mWJp8XjtlW46nhPwaCPXDErQ6Ko/Ogb1lgoIQJjqZYmVgpth1kL+FfC2BQzA8xM160dNjHSegUw62Jl1MqPuMbS3+65HNbWW5bTlVfZZpQQ7I/dT5W71X8mg3gibx4F4tJ1zDWTSTtipUQ16fezHAadGhN8+GG06WbsZjzu0uYkx4W1EMlbV1R3fB8kb3VfFX0fwY84RUvbTxyXNEM/zU8PL7SpDixekzpMXHuSv370d5DhrvylDd+afLpfLDrrKDBpJu8lgwP1nVptBGbAtsYyVgXJXmy7zM2SpLQ5cIMXRfJDxN8="
        - AWS_S3_BUCKET_NAME: "metaeducation"

deploy:
  provider: s3
  # these are set up in the global env
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME
  skip_cleanup: true
  upload-dir: travis-builds

# Force new container-based infrastructure.
# Ref: http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

addons:
    apt:
        packages:
            # For building 32b binaries on a 64b host (not necessary when we
            # build for 64b):
            - gcc-multilib
            - g++-multilib

            # For running the 32b bootstrap rebol ("r3-make") on a 64b host:
            - libc6:i386

            # For cross-compiling to Windows.
            - binutils-mingw-w64-i686
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-i686
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-i686
            - g++-mingw-w64-x86-64
            - mingw-w64


install:
    # Fetch a Rebol bootstrap binary, which is needed for building Rebol.
    - wget http://www.rebol.com/r3/downloads/r3-a111-4-2.tar.gz
    - tar xvzf r3-a111-4-2.tar.gz
    - cp r3 make/r3-make

script:
    - cd make/
    # If REL is defined and not empty, we do a release build by compiling with
    # NDEBUG defined. (`${parameter+alt_value}` is a Bash-ism documented as:
    # "if parameter set, use alt_value, else use null string.")
    - export CC="${TOOLS}${CC}${REL+ -DNDEBUG}"
    # We have to set REBOL_TOOL explicitly to circumvent the automatic r3-make
    # filename inference, as we always use a Linux r3-make, even when
    # cross-compiling to Windows.
    - make -f makefile.boot REBOL_TOOL=r3-make OS_ID="${OS_ID}" CC="${CC}"
    # A minimal sanity check that the built R3 does _something_. Eventually, we
    # should run the full test suite.

    # Run once but don't pipe output, in case it prints out useful crash msg
    - if [ "${OS_ID}" = "0.4.40" ]; then ./r3 --do 'print {OK}'; fi

    # Run a second time with piped output to return success/faiure to Travis
    - if [ "${OS_ID}" = "0.4.40" ]; then ./r3 --do 'print {OK}' | grep OK; fi
